### ISSUE TITLE
Building jars on windows fails with error: SignArchives FAILED. 

### ISSUE THREAD

**Issue by vThinkBeyondVM** [yavijava/yavijava#129] opened 2015-08-26 06:00 UTC
Steps to reproduce
1. Downloaded zip file from here :https://github.com/yavijava/yavijava/releases
2. I am using Windows 7 machine to build the jar files. 
3. Extracted the zip file and opened command line 
4. cd to the the directory where gradlew.bat is available. (on windows command line console)
5. Executed "gradlew.bat build". It took around 7 min to build the jars. 

Please refer the below snapshot: 

![signarchives failed](https://cloud.githubusercontent.com/assets/13938550/9486504/b37479e6-4be5-11e5-9495-f2a527ab3f4d.png)

**Comment by vThinkBeyondVM** [comment] 2015-08-26 06:31
I could see below jars in libs folder though

![image](https://cloud.githubusercontent.com/assets/13938550/9486826/bb8a2d3e-4be9-11e5-9c20-bfd7d3193c57.png).

And below files got created as well:

![image](https://cloud.githubusercontent.com/assets/13938550/9486850/ef8fab68-4be9-11e5-8750-2b32494e3f3a.png)

I did not try using these jars. I did not use as I have maven project with required YA VIJAVA dependencies.  As per me, it will work fine.

My JAVA version is : 1.7.0_51

**Comment by michaelrice** [comment] 2015-08-27 05:31
I have a fix I added with #124 but it may still be an issue. Im updating my windows box so I can test on Windows before I cut the next release.

**Comment by michaelrice** [comment] 2015-08-27 08:40
Just some updates here before I head to bed for the night.
1. My fixes have been tested on Mac OSX & Linux and work fine
2. The fixes are currently in the Gradle Branch via #124 
3. The testing being done is to manually edit the build.gradle file to change to 6.0.02 then run a build and see if the signing task runs. If it runs there is a bug still, if it does not run by doing a gradlew build it should be fixed.
4. Still waiting on Windows env to get updated. Im getting SSL Handshake errors because my Root CA file is so out of date.

Once the Windows update is done and I am able to validate the fix I have in place also works on Windows I will cut the 6.0.02 release and push it to Maven Central.

**Comment by michaelrice** [comment] 2015-08-28 01:34
This issue is confirmed fixed using the code in current gradle branch. I was never able to test on Windows 7, but on 2008 R2 SP1 it is no longer an issue. Ill cut a release and push it to public maven tonight. Once its been pushed it takes up to 12 hours to sync to various maven mirrors.

**Closed as completed by michaelrice** 2015-08-28 01:34 UTC
Labels: bug, Blocker
